### ISSUE TITLE
ligolw doesn't like filenames as names

### ISSUE THREAD

**Issue by bfarr** [lpsinger/observing-scenarios-simulations#2]
When running with the default setup, `pack-psds.py` fails when trying to build a REAL8FrequencySeries with a name containing a `.`.

It looks like ligolw hasn't allowed `.`s in names for some time (see, e.g., [here](https://git.ligo.org/kipp.cannon/python-ligo-lw/-/commit/767477780c8907c43fe0a5609940b32fd2824353)), so I'm not sure why this hasn't been an issue before.

**Comment by lpsinger** [comment]
This is working for me. Are you using the poetry environment, or are you using newer versions of the dependencies?

**Comment by lpsinger** [comment]
Fixed by #3.
