### ISSUE TITLE
 R&P models + rate selection

### ISSUE THREAD

**Issue by weizmannk** [lpsinger/observing-scenarios-simulations#27]
Hi @lpsinger ,

1)-  Could we please tell me , why , We use PDB (pair) model in the first row of Table II in  [GWTC-3](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048) to standardize our merger rate ? 

2)- Then  base on Amanda comment[1], could we get your opinion about this ?

[1]  << think we should say at some point the caveats associated with doing this.
For the LRR distribution, we are attaching a rate that was computed with a different mass distribution. This is not self-consistent but might be reasonable within the error bars. We should say whether this leads to an over or under-estimate.
For the GWTC-3 distribution, we are taking the rate associated with a full population fit, presumably just using the marginalized version (so the value of 240) and applying it to the max a posteriori population fit. This is also not self-consistent and I'm not sure why we are doing it. Regardless, we should say whether this leads to an over or under-estimate of the total rate of detections and the rate in each bin.>>

**Comment by lpsinger** [comment]
> 1)- Could we please tell me , why , We use PDB (pair) model in the first row of Table II in [GWTC-3](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.13.011048) to standardize our merger rate ?

Because that model uses the mass and spin distribution that is the closest match to the distributions that Amanda gave us.

> [1] << think we should say at some point the caveats associated with doing this.

Indeed. It would have made more sense if the Rates and Populations group had given us a rate estimate for the maximum a posteriori hyper parameters. Perhaps it's not too late to get that data?

**Comment by weizmannk** [comment]
@lpsinger 
According to Amanda the rate is 316.0 Gpc^-3 yr^-1  
So we  underestimate of the overall CBC rate according the rate 240 Gpc^-3 yr^-1 that we
 chose in our paper. 

**For More** 
From Amanda, 

 A rate of CBC mergers associated with the max hyperparameter draw is in the same file where the draw is defined (https://dcc.ligo.org/DocDB/0180/T2100512/006/O1O2O3all_mass_h_iid_mag_iid_tilt_powerlaw_redshift_maxP_sample.json). The rate in that file is 316.0 Gpc^-3 yr^-1 

The rate you quote in the text is 240 Gpc^-3 yr^-1 : "We normalize the initial distribution of the \texttt{GWTC-3} with the total rate density of mergers, integrated across all masses and spins, taken to be fixed at $240_{-140}^{+270}\,\mathrm{Gpc}^{-3}\mathrm{yr}^{-1}$ (which is in the first row and last column on this table). " So the rate that we use is an underestimate of the overall CBC rate. Furthermore, we know that the max hyperposterior draw has a much deeper mass gap than the bulk of the hyperposterior, so it's likely underestimating the rate of mass gap events and NSBHs in general. I'm happy to modify the text to explain this
