### ISSUE TITLE
Are there GPS times of the injections stored somewhere? 

### ISSUE THREAD

**Issue by saleem-muhammed** [lpsinger/observing-scenarios-simulations#43]
I was having a discussion with Weizmann (@weizmannk ), Michael (@mcoughlin ) (and Leo also cc'ed (@lpsinger) ) about the sensitive volumes estimated in the observing scenario updates paper (Weizmann et al). Weizmann shared the BNS injection file on which I wanted to compute the optimal SNR's of all the sources, in order to see what is coming from obvious false detections and what are not, and how that could have affected the rates predictions. (The motivation was to address some difference in the rates found in a different work that I am part of). However, there are no gps times of injections in the shared data, which makes it impossible to compute the SNR's. Is there a way to extract the gps times?

**Comment by lpsinger** [comment]
I don't know what @weizmannk sent you, but it _should_ be in the form of the data releases on Zenodo, for example: https://zenodo.org/records/7026209

You can find the event times in several places:

- `events.xml.gz` and `events.sqlite` files
- the `DATE-OBS` field in the FITS files

**Comment by saleem-muhammed** [comment]
Thanks Leo, I will take a look at them.

**Comment by saleem-muhammed** [comment]
What are the tools available in igwn environments for reading the sqlite and FITS files?
Is there any documentation that shows the structure of these files?

**Comment by lpsinger** [comment]
@saleem-muhammed, here are a few links to get you started. I see from the LIGO roster that you are a LIGO Scientific Collaboration member, so I also suggest that you join https://chat.ligo.org if you are not already a member. That's a great place to ask for help.

sqlite:

- https://lscsoft.docs.ligo.org/ligo.skymap/io/events.html
- https://git.ligo.org/kipp.cannon/python-ligo-lw
- https://gwpy.github.io/docs/stable/table/io/#gwpy-table-io-ligolw

FITS:
- https://lscsoft.docs.ligo.org/ligo.skymap/io/fits.html
- https://docs.astropy.org/en/stable/io/fits/
- https://mhealpy.readthedocs.io/en/latest/
