### ISSUE TITLE
Get significant public alerts

### ISSUE THREAD

**Issue by Hemanthb1** [lpsinger/observing-scenarios-simulations#57]
In the get public alerts.py, how to confine the search for significant events only? since O4 run has much more low significance events. I see that xml file from 'get_info' uses only three keys: classification, properties and GW skymap

**Comment by atoivonen13** [comment]
@Hemanthb1, @weizmannk and I would recommend a SNR cut of ~10 and a FAR cut based on the significant FAR threshold, which is 1/5 months for CBC events currently: https://emfollow.docs.ligo.org/userguide/analysis/index.html#alert-threshold
