### ISSUE TITLE
O4 simulations with realistic KAGRA sensitivity

### ISSUE THREAD

**Issue by Tohuvavohu** [lpsinger/observing-scenarios-simulations#9]
The paper, and simulations released, use a KAGRA PSD with a BNS range of 80 Mpc, according to Footnote 7 in the paper.
According to the latest LVK update (https://observing.docs.ligo.org/plan/): "KAGRA should be running with greater than 1 Mpc sensitivity at the beginning of O4, and will work to improve the sensitivity toward the end of O4."

For this reason, the median localization size in the simulations, are likely significantly smaller than will be seen in O4.
Thoughts?
Is it possible to produce a new O4 sim set without KAGRA, or with very low sensitivity KAGRA?

**Comment by weizmannk** [comment]
I think that here we only use the sensitivities published in the Ligo  public space,  https://dcc.ligo.org/LIGO-T2200043/public .
I mean that for a lower estimate it will have to appear on  https://dcc.ligo.org/LIGO-T2200043/public.
Also it seems that at the end of the O4 the sensitivity could reach the sensitivity initially expected. 

Maybe @lpsinger  or @mcoughlin  can explain better .

**Comment by Tohuvavohu** [comment]
@weizmannk As you point out, there are many sensitivity curves on that public page that are much more representative of the expected performance of KAGRA in O4, compared to the 80 Mpc range curve used in the paper/current sims. 
It would be very useful to use one of those (eg the 3 Mpc range curve) or just not include KAGRA at all for the O4 sims...

**Comment by Tohuvavohu** [comment]
Bump?

**Comment by Tohuvavohu** [comment]
Bump @lpsinger

**Comment by lpsinger** [comment]
We checked on the PSDs we were using with LVK operations. @mcoughlin, what was the resolution of that?

**Comment by mcoughlin** [comment]
@Tohuvavohu We are using a KAGRA leadership approved PSD, which indeed is low sensitivity for O4.

**Comment by Tohuvavohu** [comment]
Sorry, to be clear, the Petrov+Singer paper uses a KAGRA PSD that is equivalent to 80 Mpc BNS sensitivity.
Will this be updated?

**Comment by lpsinger** [comment]
Was that change #4?

**Comment by lpsinger** [comment]
The Petrov+Singer paper is published already, so we can't update the paper. The updated observing scenarios predictions which are based on the same code as the Singer & Petrov paper will use the lower sensitivity KAGRA PSD. Make sense?

**Comment by Tohuvavohu** [comment]
Yes, thank you.
